const crypto = require("crypto");
const { SignJWT, jwtVerify, importJWK, decodeProtectedHeader } = require("jose");

const SD_ALG = "sha-256";

class SDJWTError extends Error {}

function base64url(input) {
  return Buffer.from(input).toString("base64url");
}

// One disclosure is the triple [salt, claimName, claimValue], transmitted
// (and hashed) as base64url(JSON.stringify(triple)) — this is the IETF
// SD-JWT format (Section 3a). The salt exists so that two disclosures for
// the same name/value pair (e.g. isAdult: true on two different
// credentials) don't hash to the same digest, which would otherwise leak
// information by correlation.
function makeDisclosure(claimName, claimValue) {
  const salt = base64url(crypto.randomBytes(16));
  const disclosure = base64url(JSON.stringify([salt, claimName, claimValue]));
  return { salt, name: claimName, value: claimValue, disclosure };
}

// disclosure is untrusted wire input (it travels inside a presentation an
// attacker fully controls) — a malformed one must fail as SDJWTError, not
// leak a raw JSON.parse SyntaxError past this module's error contract.
function decodeDisclosure(disclosure) {
  let parsed;
  try {
    parsed = JSON.parse(Buffer.from(disclosure, "base64url").toString("utf8"));
  } catch {
    throw new SDJWTError("malformed_disclosure");
  }
  if (!Array.isArray(parsed) || parsed.length !== 3) {
    throw new SDJWTError("malformed_disclosure");
  }
  const [salt, name, value] = parsed;
  return { salt, name, value, disclosure };
}

function digestDisclosure(disclosure) {
  return crypto.createHash("sha256").update(disclosure).digest("base64url");
}

// Builds the credential: a JWT whose payload holds only the *digests* of
// each claim (_sd), never the claims themselves, plus the full set of
// disclosures returned separately for the holder's wallet. Anyone who only
// sees the JWT — including this function's own caller, once it returns —
// cannot recover a claim's value from its digest.
async function issueCredential({
  claims,
  issuerPrivateKeyJwk,
  kid,
  issuer,
  subject,
  holderPublicKeyJwk,
  expiresInSeconds,
  credentialId,
  now = Math.floor(Date.now() / 1000),
}) {
  if (!claims || typeof claims !== "object" || Array.isArray(claims) || Object.keys(claims).length === 0) {
    throw new SDJWTError("claims must be a non-empty object");
  }
  if (!Number.isFinite(expiresInSeconds) || expiresInSeconds <= 0) {
    throw new SDJWTError("expiresInSeconds must be a positive number");
  }

  const disclosures = Object.entries(claims).map(([name, value]) => makeDisclosure(name, value));
  const sd = disclosures.map((d) => digestDisclosure(d.disclosure));

  const privateKey = await importJWK(issuerPrivateKeyJwk, "EdDSA");

  const jwt = await new SignJWT({
    _sd: sd,
    _sd_alg: SD_ALG,
    // Key binding (Section 3c): the holder's own device public key travels
    // inside the signed payload, so it can't be swapped out later. A
    // presentation is only meaningful if it's signed by the matching
    // private key — that check belongs to the presentation verifier
    // (Milestone 5), not to issuance.
    ...(holderPublicKeyJwk ? { cnf: { jwk: holderPublicKeyJwk } } : {}),
  })
    .setProtectedHeader({ alg: "EdDSA", kid, typ: "sd+jwt" })
    .setIssuer(issuer)
    .setSubject(subject)
    .setIssuedAt(now)
    .setExpirationTime(now + expiresInSeconds)
    // jti = the credential's own database row id, generated by the caller
    // *before* calling this (so it can insert that same id afterward) —
    // without it, a verifier has no way to know which credential a JWT
    // corresponds to, and so no way to check it against a revocation list
    // (Section 3d). Optional only for callers that don't need revocation
    // support at all (e.g. this package's own issuance tests).
    .setJti(credentialId)
    .sign(privateKey);

  return {
    jwt,
    disclosures: disclosures.map(({ salt, name, value, disclosure }) => ({ salt, name, value, disclosure })),
  };
}

// Holder-side: narrow the full disclosure set down to what's being shared
// for one specific presentation (Section 3, the "data minimisation" demo
// beat — e.g. fullName/isAdult/idType/idLast4 and nothing else).
function selectDisclosures(disclosures, claimNames) {
  const wanted = new Set(claimNames);
  return disclosures.filter((d) => wanted.has(d.name));
}

// Verifier-side: checks the issuer's signature, then for each disclosure
// actually presented, recomputes its digest and confirms it's one of the
// digests the issuer originally signed. A disclosure whose digest isn't in
// _sd is rejected outright — it's not "unknown", it's evidence of
// tampering, so this throws rather than silently dropping it. Any claim
// never disclosed simply never appears; there is no way to derive it from
// the JWT alone, since the JWT never held anything but hashes.
async function verifyCredential({
  jwt,
  disclosures = [],
  issuerPublicKeyJwk,
  now = Math.floor(Date.now() / 1000),
}) {
  const publicKey = await importJWK(issuerPublicKeyJwk, "EdDSA");

  let payload;
  try {
    ({ payload } = await jwtVerify(jwt, publicKey, { currentDate: new Date(now * 1000) }));
  } catch (err) {
    throw new SDJWTError(`credential_invalid: ${err.message}`);
  }

  if (!Array.isArray(payload._sd) || payload._sd_alg !== SD_ALG) {
    throw new SDJWTError("credential_missing_sd_claims");
  }
  const sdSet = new Set(payload._sd);

  const claims = {};
  for (const d of disclosures) {
    const digest = digestDisclosure(d.disclosure);
    if (!sdSet.has(digest)) {
      throw new SDJWTError(`disclosure_not_in_credential: ${d.name}`);
    }
    // Derived from d.disclosure itself, not trusted from d.name/d.value as
    // the caller supplied them — every real caller already gets those by
    // decoding the same disclosure string (decodeDisclosure), so this
    // just makes that the only way to get a claim into the result,
    // instead of also trusting a second, unchecked field with the same
    // job.
    const decoded = decodeDisclosure(d.disclosure);
    claims[decoded.name] = decoded.value;
  }

  return { payload, claims };
}

function getJwtKid(jwt) {
  return decodeProtectedHeader(jwt).kid;
}

// Compact SD-JWT+KB presentation format (IETF SD-JWT): the credential JWT,
// each disclosed disclosure, and a holder-signed "key binding" JWT, joined
// by "~". This is what actually travels in a check-in QR-triggered
// presentation (Section 3, Section 9.4) — not the bare credential, which
// would just be a replayable bearer token.
const PRESENTATION_SEPARATOR = "~";

// Node-only (uses `credentials`'s own SignJWT + this module's disclosure
// encoding) — the browser wallet builds its own presentation independently
// in web/src/lib/presentation.js using only `jose`, since this file's
// top-level `require("crypto")` can't be bundled for a browser target.
// Provided here mainly so this package's own tests can construct a real
// presentation end-to-end, and for any future non-browser holder.
async function buildPresentation({ jwt, disclosures, holderPrivateKeyJwk, holderAlg = "ES256", nonce, audience, now = Math.floor(Date.now() / 1000) }) {
  const privateKey = await importJWK(holderPrivateKeyJwk, holderAlg);
  const kbJwt = await new SignJWT({ nonce, aud: audience })
    .setProtectedHeader({ alg: holderAlg })
    .setIssuedAt(now)
    .sign(privateKey);

  return [jwt, ...disclosures.map((d) => d.disclosure), kbJwt].join(PRESENTATION_SEPARATOR);
}

function decodePresentation(presentation) {
  const parts = presentation.split(PRESENTATION_SEPARATOR);
  if (parts.length < 2) {
    throw new SDJWTError("malformed_presentation");
  }
  const [jwt, ...rest] = parts;
  const kbJwt = rest[rest.length - 1];
  const disclosures = rest.slice(0, -1).map(decodeDisclosure);
  return { jwt, kbJwt, disclosures };
}

// The full presentation-side check from Section 3/9.4: verify the
// credential itself (issuer signature + expiry + disclosures, via
// verifyCredential above), then verify the key-binding JWT was signed by
// the exact device key the credential was bound to at issuance (cnf.jwk)
// — proving whoever is presenting this actually holds the device the
// credential was issued to, not just a copy of the JWT. Nonce/audience/
// freshness are Section 9.4's replay defences; the caller (api's
// checkin route) is responsible for the nonce being single-use, since
// that requires state this stateless function doesn't have.
async function verifyPresentation({
  presentation,
  issuerPublicKeyJwk,
  expectedNonce,
  expectedAudience,
  maxAgeSeconds = 90,
  now = Math.floor(Date.now() / 1000),
}) {
  const { jwt, kbJwt, disclosures } = decodePresentation(presentation);

  const { payload, claims } = await verifyCredential({ jwt, disclosures, issuerPublicKeyJwk, now });

  if (!payload.cnf || !payload.cnf.jwk) {
    throw new SDJWTError("credential_missing_key_binding");
  }

  let kbPayload;
  try {
    const holderPublicKey = await importJWK(payload.cnf.jwk, "ES256");
    ({ payload: kbPayload } = await jwtVerify(kbJwt, holderPublicKey, { currentDate: new Date(now * 1000) }));
  } catch (err) {
    throw new SDJWTError(`presentation_signature_invalid: ${err.message}`);
  }

  if (kbPayload.nonce !== expectedNonce) {
    throw new SDJWTError("nonce_mismatch");
  }
  if (kbPayload.aud !== expectedAudience) {
    throw new SDJWTError("audience_mismatch");
  }
  const age = now - kbPayload.iat;
  if (age > maxAgeSeconds || age < -5) {
    throw new SDJWTError("presentation_stale");
  }

  return { claims, credentialPayload: payload, kbPayload };
}

module.exports = {
  SDJWTError,
  issueCredential,
  selectDisclosures,
  verifyCredential,
  makeDisclosure,
  decodeDisclosure,
  digestDisclosure,
  getJwtKid,
  buildPresentation,
  decodePresentation,
  verifyPresentation,
  PRESENTATION_SEPARATOR,
};
